package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SectieAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSectieAllPropertiesEquals(Sectie expected, Sectie actual) {
        assertSectieAutoGeneratedPropertiesEquals(expected, actual);
        assertSectieAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSectieAllUpdatablePropertiesEquals(Sectie expected, Sectie actual) {
        assertSectieUpdatableFieldsEquals(expected, actual);
        assertSectieUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSectieAutoGeneratedPropertiesEquals(Sectie expected, Sectie actual) {
        assertThat(actual)
            .as("Verify Sectie auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSectieUpdatableFieldsEquals(Sectie expected, Sectie actual) {
        assertThat(actual)
            .as("Verify Sectie relevant properties")
            .satisfies(a -> assertThat(a.getNume()).as("check nume").isEqualTo(expected.getNume()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSectieUpdatableRelationshipsEquals(Sectie expected, Sectie actual) {
        // empty method
    }
}
